submit_script: submit/dkfz/submit.sh
script: apps/eval.py
script_args: config=config/eval/auc.yaml task_input=forward
script_overrides:
  task_args.disease_lst:
    - config/disease_list/i._infectious_diseases.yaml
    - config/disease_list/ii._neoplasms.yaml
    - 'config/disease_list/iii._blood_&_immune_disorders.yaml'
    - config/disease_list/iv._metabolic_diseases.yaml
    - config/disease_list/ix._circulatory_diseases.yaml
    - config/disease_list/v._mental_disorders.yaml
    - config/disease_list/vi._nervous_system_diseases.yaml
    - config/disease_list/vii._eye_diseases.yaml
    - config/disease_list/viii._ear_diseases.yaml
    - config/disease_list/x._respiratory_diseases.yaml
    - config/disease_list/xi._digestive_diseases.yaml
    - config/disease_list/xii._skin_diseases.yaml
    - config/disease_list/xiii._musculoskeletal_diseases.yaml
    - config/disease_list/xiv._genitourinary_diseases.yaml
    - 'config/disease_list/xv._pregnancy_&_childbirth.yaml'
    - config/disease_list/xvi._perinatal_conditions.yaml
    - config/disease_list/xvii._congenital_abnormalities.yaml
    - config/disease_list/death.yaml
  ckpt:
    - ${oc.env:DELPHI_CKPT_DIR}/prs/delphi-ckpt/delphi-no-prs
    - ${oc.env:DELPHI_CKPT_DIR}/prs/delphi-ckpt/delphi
    - ${oc.env:DELPHI_CKPT_DIR}/prs/delphi-ckpt/delphi-prs-mlp
memory: 24
gpu: false
queue: long