submit_script: ${oc.env:DELPHI_ROOT_DIR}/submit/dkfz/submit.sh
script: ${oc.env:DELPHI_ROOT_DIR}/apps/forward.py
script_args: config=config/forward.yaml device=cuda log.wandb_log=true name=forward
script_overrides:
  - ckpt=${oc.env:DELPHI_CKPT_DIR}/prs/delphi-ckpt/delphi data.prs.include=true
  - ckpt=${oc.env:DELPHI_CKPT_DIR}/prs/delphi-ckpt/delphi-prs-mlp data.prs.include=true
  - ckpt=${oc.env:DELPHI_CKPT_DIR}/prs/delphi-ckpt/delphi-no-prs data.prs.include=false
memory: 16
gpu: true
gpu_num: 1
j_exclusive: true
gpu_mem: 10
queue: gpu-debian