# - script: apps/generate.py
#   script_args: config=config/gen.yaml ckpt=${oc.env:DELPHI_CKPT_DIR}/delphi-zero-inflate device=cuda start_age_in_years=60 name=60
#   memory: 16
#   gpu: true
#   gpu_num: 1
#   j_exclusive: true
#   gpu_mem: 10
#   queue: gpu-debian
# - script: apps/generate.py
#   script_args: config=config/gen.yaml ckpt=${oc.env:DELPHI_CKPT_DIR}/delphi-zero-inflate device=cuda start_age_in_years=40 name=40
#   memory: 16
#   gpu: true
#   gpu_num: 1
#   j_exclusive: true
#   gpu_mem: 10
#   queue: gpu-debian
# - script: apps/generate.py
#   script_args: config=config/gen.yaml ckpt=${oc.env:DELPHI_CKPT_DIR}/delphi-zero-inflate device=cuda start_age_in_years=20 name=20
#   memory: 16
#   gpu: true
#   gpu_num: 1
#   j_exclusive: true
#   gpu_mem: 10
#   queue: gpu-debian
# - script: apps/generate.py
#   script_args: config=config/gen.yaml ckpt=${oc.env:DELPHI_CKPT_DIR}/delphi device=cuda start_age_in_years=60 sampler.zero_inflate=false
#   memory: 16
#   gpu: true
#   gpu_num: 1
#   j_exclusive: true
#   gpu_mem: 10
#   queue: gpu-debian
# - script: apps/generate.py
#   script_args: config=config/gen.yaml ckpt=${oc.env:DELPHI_CKPT_DIR}/delphi device=cuda start_age_in_years=40 sampler.zero_inflate=false
#   memory: 16
#   gpu: true
#   gpu_num: 1
#   j_exclusive: true
#   gpu_mem: 10
#   queue: gpu-debian
# - script: apps/generate.py
#   script_args: config=config/gen.yaml ckpt=${oc.env:DELPHI_CKPT_DIR}/delphi device=cuda start_age_in_years=20 sampler.zero_inflate=false
#   memory: 16
#   gpu: true
#   gpu_num: 1
#   j_exclusive: true
#   gpu_mem: 10
#   queue: gpu-debian
submit_script: ${oc.env:DELPHI_ROOT_DIR}/submit/dkfz/submit.sh
script: ${oc.env:DELPHI_ROOT_DIR}/apps/generate.py
script_args: config=config/gen.yaml ckpt=${oc.env:DELPHI_CKPT_DIR}/delphi device=cuda sampler.zero_inflate=false
script_overrides:
  - start_age_in_years=40
  - start_age_in_years=45
  - start_age_in_years=50
  - start_age_in_years=55
  - start_age_in_years=60
  - start_age_in_years=65
  - start_age_in_years=70
  - start_age_in_years=75
memory: 16
gpu: true
gpu_num: 1
j_exclusive: true
gpu_mem: 10
queue: gpu-debian